"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { authApi } from "../../auth-provider";
import { parseTriviaSpreadsheet, type SpreadsheetCell } from "../../../lib/trivia-import";
import {
  createEmptyTriviaQuiz,
  createTriviaQuestion,
  questionTypeLabels,
  triviaTimerPresets,
  type TriviaQuestion,
  type TriviaQuestionType,
  type TriviaQuiz,
} from "../../../lib/trivia";

const answerColors = ["red", "blue", "yellow", "green", "violet", "cyan"];

function SelectField({ label, value, onChange, children }: { label: string; value: string | number; onChange: (value: string) => void; children: React.ReactNode }) {
  return <label className="builder-field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)}>{children}</select></label>;
}

function QuestionRail({ quiz, selectedId, onSelect, onAdd, onMove, onDelete }: { quiz: TriviaQuiz; selectedId: string; onSelect: (id: string) => void; onAdd: () => void; onMove: (from: number, to: number) => void; onDelete: (id: string) => void }) {
  const [dragged, setDragged] = useState<number | null>(null);
  return <aside className="question-rail"><header><span>Câu hỏi</span><b>{quiz.questions.length}</b></header><div className="question-rail-list">{quiz.questions.map((question, index) => <button draggable key={question.id} className={selectedId === question.id ? "active" : ""} onClick={() => onSelect(question.id)} onDragStart={() => setDragged(index)} onDragOver={event => event.preventDefault()} onDrop={() => { if (dragged !== null) onMove(dragged, index); setDragged(null); }}><i>⋮⋮</i><b>{String(index + 1).padStart(2, "0")}</b><span>{question.prompt || "Câu hỏi chưa có nội dung"}<small>{questionTypeLabels[question.type]} · {question.timeLimitSeconds}s</small></span><em onClick={event => { event.stopPropagation(); onDelete(question.id); }}>×</em></button>)}</div><button className="add-question" onClick={onAdd}>＋ Thêm câu hỏi</button></aside>;
}

function AnswerEditor({ question, onChange }: { question: TriviaQuestion; onChange: (question: TriviaQuestion) => void }) {
  const setOptions = (options: TriviaQuestion["options"]) => onChange({ ...question, options });
  const toggleCorrect = (index: number) => setOptions(question.options.map((option, optionIndex) => ({ ...option, correct: optionIndex === index ? !option.correct : (["SINGLE_CHOICE", "TRUE_FALSE", "IMAGE_CHOICE"].includes(question.type) ? false : option.correct) })));
  if (question.type === "TEXT_INPUT") return <div className="accepted-answer-editor"><label>Đáp án được chấp nhận</label>{(question.config.acceptedAnswers ?? [""]).map((answer, index) => <div key={index}><input value={answer} onChange={event => { const accepted = [...(question.config.acceptedAnswers ?? [])]; accepted[index] = event.target.value; onChange({ ...question, config: { ...question.config, acceptedAnswers: accepted } }); }} /><button onClick={() => onChange({ ...question, config: { ...question.config, acceptedAnswers: question.config.acceptedAnswers?.filter((_, itemIndex) => itemIndex !== index) } })}>×</button></div>)}<button onClick={() => onChange({ ...question, config: { ...question.config, acceptedAnswers: [...(question.config.acceptedAnswers ?? []), ""] } })}>＋ Thêm cách viết</button><div className="normalization-options"><label><input type="checkbox" checked={question.config.caseInsensitive !== false} onChange={event => onChange({ ...question, config: { ...question.config, caseInsensitive: event.target.checked } })}/> Không phân biệt hoa thường</label><label><input type="checkbox" checked={question.config.accentInsensitive === true} onChange={event => onChange({ ...question, config: { ...question.config, accentInsensitive: event.target.checked } })}/> Không phân biệt dấu</label></div></div>;
  if (question.type === "NUMBER_INPUT") return <div className="number-config"><SelectField label="Cách chấm" value={question.config.numberMode ?? "EXACT"} onChange={value => onChange({ ...question, config: { ...question.config, numberMode: value as "EXACT" | "RANGE" } })}><option value="EXACT">Chính xác / dung sai</option><option value="RANGE">Khoảng giá trị</option></SelectField>{question.config.numberMode === "RANGE" ? <div><label>Từ<input type="number" value={question.config.numberMinimum ?? 0} onChange={event => onChange({ ...question, config: { ...question.config, numberMinimum: Number(event.target.value) } })}/></label><label>Đến<input type="number" value={question.config.numberMaximum ?? 10} onChange={event => onChange({ ...question, config: { ...question.config, numberMaximum: Number(event.target.value) } })}/></label></div> : <div><label>Đáp án<input type="number" value={question.config.numberAnswer ?? 0} onChange={event => onChange({ ...question, config: { ...question.config, numberAnswer: Number(event.target.value) } })}/></label><label>Dung sai<input type="number" value={question.config.tolerance ?? 0} onChange={event => onChange({ ...question, config: { ...question.config, tolerance: Number(event.target.value) } })}/></label></div>}</div>;
  if (question.type === "SCALE") return <div className="scale-editor"><div><label>Từ<input type="number" value={question.config.scaleMinimum ?? 1} onChange={event => onChange({ ...question, config: { ...question.config, scaleMinimum: Number(event.target.value) } })}/></label><label>Đến<input type="number" value={question.config.scaleMaximum ?? 10} onChange={event => onChange({ ...question, config: { ...question.config, scaleMaximum: Number(event.target.value) } })}/></label></div><input type="range" min={question.config.scaleMinimum ?? 1} max={question.config.scaleMaximum ?? 10} defaultValue={5}/><div><input placeholder="Không thích" value={question.config.scaleMinimumLabel ?? ""} onChange={event => onChange({ ...question, config: { ...question.config, scaleMinimumLabel: event.target.value } })}/><input placeholder="Rất thích" value={question.config.scaleMaximumLabel ?? ""} onChange={event => onChange({ ...question, config: { ...question.config, scaleMaximumLabel: event.target.value } })}/></div></div>;
  return <div className="builder-answers">{question.options.map((option, index) => <div className={`builder-answer ${answerColors[index % answerColors.length]}`} key={option.id}><i>⋮⋮</i>{question.type === "IMAGE_CHOICE" && <button className="answer-image">＋ Hình</button>}<input value={option.text ?? ""} onChange={event => setOptions(question.options.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))}/>{question.type !== "POLL" && <button className={option.correct ? "correct" : ""} onClick={() => toggleCorrect(index)} aria-label="Đáp án đúng">✓</button>}<button onClick={() => setOptions(question.options.filter((_, itemIndex) => itemIndex !== index))}>×</button></div>)}{!(["TRUE_FALSE"].includes(question.type)) && <button className="add-answer" onClick={() => setOptions([...question.options, { id: `${question.id}-option-${Date.now()}`, text: `Đáp án ${question.options.length + 1}`, correct: false }])}>＋ Thêm đáp án</button>}</div>;
}

function ExcelImporter({ onClose, onImported }: { onClose: () => void; onImported: (questions: TriviaQuestion[], mode: "replace" | "append") => void }) {
  const [fileName, setFileName] = useState(""); const [questions, setQuestions] = useState<TriviaQuestion[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function readFile(file?: File) { if (!file) return; setBusy(true); setError(""); setQuestions([]); setFileName(file.name); try { const { default: readXlsxFile } = await import("read-excel-file"); const rows = await readXlsxFile(file, { sheet: "Cau hoi" }); setQuestions(parseTriviaSpreadsheet(rows as SpreadsheetCell[][])); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đọc file Excel."); } finally { setBusy(false); } }
  const counts = questions.reduce<Record<string, number>>((result, question) => ({ ...result, [question.type]: (result[question.type] ?? 0) + 1 }), {});
  return <div className="builder-modal-backdrop"><section className="ai-generator-modal excel-import-modal"><header><span>📊</span><div><small>EXCEL QUIZ IMPORT</small><h2>Nhập câu hỏi từ Excel</h2></div><button onClick={onClose}>×</button></header><div className="excel-import-steps"><p><b>1.</b> Tải file mẫu và xem sheet <strong>Huong dan</strong>.</p><p><b>2.</b> Nhập mỗi câu hỏi trên một dòng trong sheet <strong>Cau hoi</strong>.</p><p><b>3.</b> Chọn file bên dưới; dữ liệu chỉ được chèn khi toàn bộ file hợp lệ.</p></div><Link className="excel-template-link" href="/templates/luki-quiz-import-template.xlsx" download>⬇ Tải file Excel mẫu</Link><label className="excel-file-picker"><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event => void readFile(event.target.files?.[0])}/><span>{busy ? "Đang kiểm tra file…" : fileName || "Chọn file .xlsx"}</span></label><div className="excel-format-help"><b>correct_answers:</b><span>Một đáp án: <code>1</code> · Nhiều đáp án: <code>1,2,4</code> · Điền chữ: <code>Hà Nội|Ha Noi</code> · Sắp xếp: để trống.</span></div>{error && <pre className="field-error excel-import-errors">{error}</pre>}{questions.length > 0 && <div className="excel-import-summary"><b>✓ {questions.length} câu hỏi hợp lệ</b><span>{Object.entries(counts).map(([type, count]) => `${questionTypeLabels[type as TriviaQuestionType]}: ${count}`).join(" · ")}</span><div>{questions.slice(0, 3).map((question, index) => <p key={question.id}>{index + 1}. {question.prompt}</p>)}</div><footer><button onClick={() => onImported(questions, "append")}>＋ Thêm vào cuối</button><button className="button" onClick={() => onImported(questions, "replace")}>Thay thế bộ hiện tại</button></footer></div>}</section></div>;
}

export function TriviaBuilder() {
  const [quiz, setQuiz] = useState<TriviaQuiz>(() => createEmptyTriviaQuiz()); const [selectedId, setSelectedId] = useState(quiz.questions[0].id); const [showExcel, setShowExcel] = useState(false); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const params = new URLSearchParams(location.search); queueMicrotask(() => setShowExcel(params.get("import") === "excel")); const id = params.get("id"); if (id) authApi<{ quiz?: TriviaQuiz }>(`/api/trivia/quizzes/${encodeURIComponent(id)}`).then((data) => { if (data.quiz) { setQuiz(data.quiz); setSelectedId(data.quiz.questions[0]?.id ?? ""); } }).catch(reason => setNotice(reason instanceof Error ? reason.message : "Không thể tải quiz từ máy chủ.")); }, []);
  const selected = useMemo(() => quiz.questions.find(question => question.id === selectedId) ?? quiz.questions[0], [quiz, selectedId]);
  function updateQuestion(next: TriviaQuestion) { setQuiz(current => ({ ...current, questions: current.questions.map(question => question.id === next.id ? next : question) })); }
  function changeType(type: TriviaQuestionType) { const template = createTriviaQuestion(type); updateQuestion({ ...template, id: selected.id, prompt: selected.prompt, description: selected.description, category: selected.category, difficulty: selected.difficulty, tags: selected.tags, timeLimitSeconds: selected.timeLimitSeconds }); }
  function addQuestion() { const next = createTriviaQuestion("SINGLE_CHOICE", quiz.questions.length); setQuiz(current => ({ ...current, questions: [...current.questions, next] })); setSelectedId(next.id); }
  function moveQuestion(from: number, to: number) { setQuiz(current => { const questions = [...current.questions]; const [moved] = questions.splice(from, 1); questions.splice(to, 0, moved); return { ...current, questions }; }); }
  async function save() { setSaving(true); setNotice(""); try { const data = await authApi<{ quiz: TriviaQuiz }>(`/api/trivia/quizzes/${quiz.id}`, { method: "PUT", body: JSON.stringify(quiz) }); setQuiz(data.quiz); setNotice("✓ Đã lưu bộ câu hỏi"); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Không thể lưu"); } finally { setSaving(false); } }
  if (!selected) return null;
  return <main className="trivia-builder">
    <header className="builder-topbar"><Link className="trivia-brand" href="/trivia"><span>L</span>LUKI TRIVIA</Link><input className="quiz-title-input" value={quiz.title} onChange={event => setQuiz({ ...quiz, title: event.target.value })}/><div><span className="save-status">{notice}</span><button className="ai-mini-button" onClick={() => setShowExcel(true)}>📊 Nhập Excel</button><button className="button" onClick={save} disabled={saving}>{saving ? "Đang lưu…" : "Lưu quiz"}</button><Link className="preview-button" href={`/create?game=trivia&quiz=${quiz.id}`}>▶ Chơi thử</Link></div></header>
    <div className="builder-layout"><QuestionRail quiz={quiz} selectedId={selected.id} onSelect={setSelectedId} onAdd={addQuestion} onMove={moveQuestion} onDelete={id => { if (quiz.questions.length === 1) return; const questions = quiz.questions.filter(question => question.id !== id); setQuiz({ ...quiz, questions }); setSelectedId(questions[0].id); }}/>
      <section className="question-editor"><div className="question-editor-heading"><span>Câu {quiz.questions.findIndex(question => question.id === selected.id) + 1}</span><button onClick={() => setShowExcel(true)}>📊 Nhập từ Excel</button></div><label className="question-prompt"><span>Câu hỏi</span><textarea value={selected.prompt} onChange={event => updateQuestion({ ...selected, prompt: event.target.value })} placeholder="Nhập câu hỏi… (Shift + Enter để xuống hàng)"/><small>Shift + Enter để xuống hàng · câu hỏi sẽ là tiêu điểm trên màn hình chơi</small></label><label className="question-description"><span>Mô tả / gợi ý (không bắt buộc)</span><textarea value={selected.description ?? ""} onChange={event => updateQuestion({ ...selected, description: event.target.value })}/></label><button className="add-media">🖼 ＋ Thêm hình ảnh, GIF hoặc video</button><div className="answer-heading"><div><span>Đáp án</span><small>{selected.type === "MULTIPLE_CHOICE" ? "Có thể đánh dấu nhiều đáp án đúng" : selected.type === "POLL" || selected.type === "SCALE" ? "Câu hỏi ý kiến — không tính điểm" : "Đánh dấu câu trả lời đúng"}</small></div></div><AnswerEditor question={selected} onChange={updateQuestion}/><label className="explanation-editor"><span>Giải thích sau khi trả lời</span><textarea value={selected.explanation ?? ""} onChange={event => updateQuestion({ ...selected, explanation: event.target.value })} placeholder="Vì sao đây là đáp án đúng?"/></label></section>
      <aside className="question-settings"><header>Cài đặt câu hỏi</header><SelectField label="Loại câu hỏi" value={selected.type} onChange={value => changeType(value as TriviaQuestionType)}>{Object.entries(questionTypeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</SelectField><SelectField label="Thời gian" value={selected.timeLimitSeconds} onChange={value => updateQuestion({ ...selected, timeLimitSeconds: Number(value) })}>{triviaTimerPresets.map(value => <option value={value} key={value}>{value} giây</option>)}</SelectField><SelectField label="Chế độ điểm" value={selected.scoringMode} onChange={value => updateQuestion({ ...selected, scoringMode: value as TriviaQuestion["scoringMode"] })}><option value="STANDARD">Chuẩn · tối đa 1000</option><option value="ACCURACY_ONLY">Chỉ độ chính xác · 1000</option><option value="DOUBLE_POINTS">Nhân đôi · tối đa 2000</option><option value="NO_POINTS">Không tính điểm</option></SelectField><SelectField label="Độ khó" value={selected.difficulty} onChange={value => updateQuestion({ ...selected, difficulty: value as TriviaQuestion["difficulty"] })}><option value="EASY">Dễ</option><option value="MEDIUM">Trung bình</option><option value="HARD">Khó</option></SelectField><label className="builder-field"><span>Danh mục</span><input value={selected.category ?? ""} onChange={event => updateQuestion({ ...selected, category: event.target.value })}/></label><label className="setting-toggle"><input type="checkbox" checked={selected.config.allowAnswerChanges ?? false} onChange={event => updateQuestion({ ...selected, config: { ...selected.config, allowAnswerChanges: event.target.checked } })}/><span/><div>Cho phép đổi đáp án<small>Mặc định tắt để khóa ngay khi gửi</small></div></label><hr/><header>Cài đặt bộ quiz</header><SelectField label="Hiển thị" value={quiz.visibility} onChange={value => setQuiz({ ...quiz, visibility: value as TriviaQuiz["visibility"] })}><option value="PRIVATE">Riêng tư</option><option value="UNLISTED">Không công khai</option><option value="PUBLIC">Công khai</option></SelectField><label className="setting-toggle"><input type="checkbox" checked={quiz.settings.shuffleQuestions} onChange={event => setQuiz({ ...quiz, settings: { ...quiz.settings, shuffleQuestions: event.target.checked } })}/><span/><div>Trộn câu hỏi</div></label><label className="setting-toggle"><input type="checkbox" checked={quiz.settings.shuffleAnswers} onChange={event => setQuiz({ ...quiz, settings: { ...quiz.settings, shuffleAnswers: event.target.checked } })}/><span/><div>Trộn đáp án</div></label><label className="setting-toggle"><input type="checkbox" checked={quiz.settings.autoAdvance} onChange={event => setQuiz({ ...quiz, settings: { ...quiz.settings, autoAdvance: event.target.checked } })}/><span/><div>Tự động chuyển câu</div></label></aside>
    </div>{showExcel && <ExcelImporter onClose={() => setShowExcel(false)} onImported={(questions, mode) => { setQuiz(current => ({ ...current, questions: mode === "replace" ? questions : [...current.questions, ...questions] })); setSelectedId(questions[0]?.id ?? selectedId); setNotice(`✓ Đã nhập ${questions.length} câu hỏi từ Excel — hãy kiểm tra trước khi lưu.`); setShowExcel(false); }}/>}</main>;
}
