"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { authApi } from "../../auth-provider";
import {
  createEmptyTriviaQuiz,
  createTriviaQuestion,
  questionTypeLabels,
  triviaTimerPresets,
  type TriviaQuestion,
  type TriviaQuestionType,
  type TriviaQuiz,
} from "../../../lib/trivia";

const answerColors = ["red", "blue", "yellow", "green", "violet", "cyan"];

function SelectField({ label, value, onChange, children }: { label: string; value: string | number; onChange: (value: string) => void; children: React.ReactNode }) {
  return <label className="builder-field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)}>{children}</select></label>;
}

function QuestionRail({ quiz, selectedId, onSelect, onAdd, onMove, onDelete }: { quiz: TriviaQuiz; selectedId: string; onSelect: (id: string) => void; onAdd: () => void; onMove: (from: number, to: number) => void; onDelete: (id: string) => void }) {
  const [dragged, setDragged] = useState<number | null>(null);
  return <aside className="question-rail"><header><span>Câu hỏi</span><b>{quiz.questions.length}</b></header><div className="question-rail-list">{quiz.questions.map((question, index) => <button draggable key={question.id} className={selectedId === question.id ? "active" : ""} onClick={() => onSelect(question.id)} onDragStart={() => setDragged(index)} onDragOver={event => event.preventDefault()} onDrop={() => { if (dragged !== null) onMove(dragged, index); setDragged(null); }}><i>⋮⋮</i><b>{String(index + 1).padStart(2, "0")}</b><span>{question.prompt || "Câu hỏi chưa có nội dung"}<small>{questionTypeLabels[question.type]} · {question.timeLimitSeconds}s</small></span><em onClick={event => { event.stopPropagation(); onDelete(question.id); }}>×</em></button>)}</div><button className="add-question" onClick={onAdd}>＋ Thêm câu hỏi</button></aside>;
}

function AnswerEditor({ question, onChange }: { question: TriviaQuestion; onChange: (question: TriviaQuestion) => void }) {
  const setOptions = (options: TriviaQuestion["options"]) => onChange({ ...question, options });
  const toggleCorrect = (index: number) => setOptions(question.options.map((option, optionIndex) => ({ ...option, correct: optionIndex === index ? !option.correct : (["SINGLE_CHOICE", "TRUE_FALSE", "IMAGE_CHOICE"].includes(question.type) ? false : option.correct) })));
  if (question.type === "TEXT_INPUT") return <div className="accepted-answer-editor"><label>Đáp án được chấp nhận</label>{(question.config.acceptedAnswers ?? [""]).map((answer, index) => <div key={index}><input value={answer} onChange={event => { const accepted = [...(question.config.acceptedAnswers ?? [])]; accepted[index] = event.target.value; onChange({ ...question, config: { ...question.config, acceptedAnswers: accepted } }); }} /><button onClick={() => onChange({ ...question, config: { ...question.config, acceptedAnswers: question.config.acceptedAnswers?.filter((_, itemIndex) => itemIndex !== index) } })}>×</button></div>)}<button onClick={() => onChange({ ...question, config: { ...question.config, acceptedAnswers: [...(question.config.acceptedAnswers ?? []), ""] } })}>＋ Thêm cách viết</button><div className="normalization-options"><label><input type="checkbox" checked={question.config.caseInsensitive !== false} onChange={event => onChange({ ...question, config: { ...question.config, caseInsensitive: event.target.checked } })}/> Không phân biệt hoa thường</label><label><input type="checkbox" checked={question.config.accentInsensitive === true} onChange={event => onChange({ ...question, config: { ...question.config, accentInsensitive: event.target.checked } })}/> Không phân biệt dấu</label></div></div>;
  if (question.type === "NUMBER_INPUT") return <div className="number-config"><SelectField label="Cách chấm" value={question.config.numberMode ?? "EXACT"} onChange={value => onChange({ ...question, config: { ...question.config, numberMode: value as "EXACT" | "RANGE" } })}><option value="EXACT">Chính xác / dung sai</option><option value="RANGE">Khoảng giá trị</option></SelectField>{question.config.numberMode === "RANGE" ? <div><label>Từ<input type="number" value={question.config.numberMinimum ?? 0} onChange={event => onChange({ ...question, config: { ...question.config, numberMinimum: Number(event.target.value) } })}/></label><label>Đến<input type="number" value={question.config.numberMaximum ?? 10} onChange={event => onChange({ ...question, config: { ...question.config, numberMaximum: Number(event.target.value) } })}/></label></div> : <div><label>Đáp án<input type="number" value={question.config.numberAnswer ?? 0} onChange={event => onChange({ ...question, config: { ...question.config, numberAnswer: Number(event.target.value) } })}/></label><label>Dung sai<input type="number" value={question.config.tolerance ?? 0} onChange={event => onChange({ ...question, config: { ...question.config, tolerance: Number(event.target.value) } })}/></label></div>}</div>;
  if (question.type === "SCALE") return <div className="scale-editor"><div><label>Từ<input type="number" value={question.config.scaleMinimum ?? 1} onChange={event => onChange({ ...question, config: { ...question.config, scaleMinimum: Number(event.target.value) } })}/></label><label>Đến<input type="number" value={question.config.scaleMaximum ?? 10} onChange={event => onChange({ ...question, config: { ...question.config, scaleMaximum: Number(event.target.value) } })}/></label></div><input type="range" min={question.config.scaleMinimum ?? 1} max={question.config.scaleMaximum ?? 10} defaultValue={5}/><div><input placeholder="Không thích" value={question.config.scaleMinimumLabel ?? ""} onChange={event => onChange({ ...question, config: { ...question.config, scaleMinimumLabel: event.target.value } })}/><input placeholder="Rất thích" value={question.config.scaleMaximumLabel ?? ""} onChange={event => onChange({ ...question, config: { ...question.config, scaleMaximumLabel: event.target.value } })}/></div></div>;
  return <div className="builder-answers">{question.options.map((option, index) => <div className={`builder-answer ${answerColors[index % answerColors.length]}`} key={option.id}><i>⋮⋮</i>{question.type === "IMAGE_CHOICE" && <button className="answer-image">＋ Hình</button>}<input value={option.text ?? ""} onChange={event => setOptions(question.options.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))}/>{question.type !== "POLL" && <button className={option.correct ? "correct" : ""} onClick={() => toggleCorrect(index)} aria-label="Đáp án đúng">✓</button>}<button onClick={() => setOptions(question.options.filter((_, itemIndex) => itemIndex !== index))}>×</button></div>)}{!(["TRUE_FALSE"].includes(question.type)) && <button className="add-answer" onClick={() => setOptions([...question.options, { id: `${question.id}-option-${Date.now()}`, text: `Đáp án ${question.options.length + 1}`, correct: false }])}>＋ Thêm đáp án</button>}</div>;
}

function AiGenerator({ onClose, onGenerated }: { onClose: () => void; onGenerated: (questions: TriviaQuestion[]) => void }) {
  const [topic, setTopic] = useState("Kiến thức Việt Nam"); const [difficulty, setDifficulty] = useState("MIXED"); const [count, setCount] = useState(10); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [types, setTypes] = useState<TriviaQuestionType[]>(["SINGLE_CHOICE", "TRUE_FALSE", "TEXT_INPUT", "MULTIPLE_CHOICE"]);
  async function generate() { setBusy(true); setError(""); try { const data = await authApi<{ questions: TriviaQuestion[] }>("/api/trivia/generate", { method: "POST", body: JSON.stringify({ topic, language: "Vietnamese", difficulty, count, types }) }); onGenerated(data.questions); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tạo câu hỏi"); } finally { setBusy(false); } }
  return <div className="builder-modal-backdrop"><section className="ai-generator-modal"><header><span>✨</span><div><small>AI QUIZ STUDIO</small><h2>Tạo bộ câu hỏi trong vài phút</h2></div><button onClick={onClose}>×</button></header><label>Chủ đề<textarea value={topic} onChange={event => setTopic(event.target.value)} placeholder="Anime, địa lý thế giới, ẩm thực…"/></label><div className="ai-grid"><SelectField label="Độ khó" value={difficulty} onChange={setDifficulty}><option value="EASY">Dễ</option><option value="MEDIUM">Trung bình</option><option value="HARD">Khó</option><option value="MIXED">Hỗn hợp</option></SelectField><SelectField label="Số câu" value={count} onChange={value => setCount(Number(value))}>{[5, 10, 15, 20, 30].map(value => <option key={value}>{value}</option>)}</SelectField></div><fieldset><legend>Loại câu hỏi</legend>{(["SINGLE_CHOICE", "TRUE_FALSE", "TEXT_INPUT", "MULTIPLE_CHOICE", "ORDER"] as TriviaQuestionType[]).map(type => <label key={type}><input type="checkbox" checked={types.includes(type)} onChange={event => setTypes(event.target.checked ? [...types, type] : types.filter(item => item !== type))}/>{questionTypeLabels[type]}</label>)}</fieldset><p>AI tạo bản nháp và luôn đưa vào Builder để bạn kiểm tra trước khi xuất bản.</p>{error && <div className="field-error">{error}</div>}<button className="button" onClick={generate} disabled={busy || !topic.trim() || !types.length}>{busy ? "Đang tạo…" : "✨ Tạo bộ câu hỏi"}</button></section></div>;
}

export function TriviaBuilder() {
  const [quiz, setQuiz] = useState<TriviaQuiz>(() => createEmptyTriviaQuiz()); const [selectedId, setSelectedId] = useState(quiz.questions[0].id); const [showAi, setShowAi] = useState(false); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const params = new URLSearchParams(location.search); queueMicrotask(() => setShowAi(params.get("ai") === "1")); const id = params.get("id"); if (id) authApi<{ quiz?: TriviaQuiz }>(`/api/trivia/quizzes/${encodeURIComponent(id)}`).then((data) => { if (data.quiz) { setQuiz(data.quiz); setSelectedId(data.quiz.questions[0]?.id ?? ""); } }).catch(reason => setNotice(reason instanceof Error ? reason.message : "Không thể tải quiz từ máy chủ.")); }, []);
  const selected = useMemo(() => quiz.questions.find(question => question.id === selectedId) ?? quiz.questions[0], [quiz, selectedId]);
  function updateQuestion(next: TriviaQuestion) { setQuiz(current => ({ ...current, questions: current.questions.map(question => question.id === next.id ? next : question) })); }
  function changeType(type: TriviaQuestionType) { const template = createTriviaQuestion(type); updateQuestion({ ...template, id: selected.id, prompt: selected.prompt, description: selected.description, category: selected.category, difficulty: selected.difficulty, tags: selected.tags, timeLimitSeconds: selected.timeLimitSeconds }); }
  function addQuestion() { const next = createTriviaQuestion("SINGLE_CHOICE", quiz.questions.length); setQuiz(current => ({ ...current, questions: [...current.questions, next] })); setSelectedId(next.id); }
  function moveQuestion(from: number, to: number) { setQuiz(current => { const questions = [...current.questions]; const [moved] = questions.splice(from, 1); questions.splice(to, 0, moved); return { ...current, questions }; }); }
  async function save() { setSaving(true); setNotice(""); try { const data = await authApi<{ quiz: TriviaQuiz }>(`/api/trivia/quizzes/${quiz.id}`, { method: "PUT", body: JSON.stringify(quiz) }); setQuiz(data.quiz); setNotice("✓ Đã lưu bộ câu hỏi"); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Không thể lưu"); } finally { setSaving(false); } }
  if (!selected) return null;
  return <main className="trivia-builder">
    <header className="builder-topbar"><Link className="trivia-brand" href="/trivia"><span>L</span>LUKI TRIVIA</Link><input className="quiz-title-input" value={quiz.title} onChange={event => setQuiz({ ...quiz, title: event.target.value })}/><div><span className="save-status">{notice}</span><button className="ai-mini-button" onClick={() => setShowAi(true)}>✨ AI</button><button className="button" onClick={save} disabled={saving}>{saving ? "Đang lưu…" : "Lưu quiz"}</button><Link className="preview-button" href={`/create?game=trivia&quiz=${quiz.id}`}>▶ Chơi thử</Link></div></header>
    <div className="builder-layout"><QuestionRail quiz={quiz} selectedId={selected.id} onSelect={setSelectedId} onAdd={addQuestion} onMove={moveQuestion} onDelete={id => { if (quiz.questions.length === 1) return; const questions = quiz.questions.filter(question => question.id !== id); setQuiz({ ...quiz, questions }); setSelectedId(questions[0].id); }}/>
      <section className="question-editor"><div className="question-editor-heading"><span>Câu {quiz.questions.findIndex(question => question.id === selected.id) + 1}</span><button onClick={async () => { setShowAi(true); }}>✨ Gợi ý bằng AI</button></div><label className="question-prompt"><span>Câu hỏi</span><textarea value={selected.prompt} onChange={event => updateQuestion({ ...selected, prompt: event.target.value })} placeholder="Nhập câu hỏi… (Shift + Enter để xuống hàng)"/><small>Shift + Enter để xuống hàng · câu hỏi sẽ là tiêu điểm trên màn hình chơi</small></label><label className="question-description"><span>Mô tả / gợi ý (không bắt buộc)</span><textarea value={selected.description ?? ""} onChange={event => updateQuestion({ ...selected, description: event.target.value })}/></label><button className="add-media">🖼 ＋ Thêm hình ảnh, GIF hoặc video</button><div className="answer-heading"><div><span>Đáp án</span><small>{selected.type === "MULTIPLE_CHOICE" ? "Có thể đánh dấu nhiều đáp án đúng" : selected.type === "POLL" || selected.type === "SCALE" ? "Câu hỏi ý kiến — không tính điểm" : "Đánh dấu câu trả lời đúng"}</small></div></div><AnswerEditor question={selected} onChange={updateQuestion}/><label className="explanation-editor"><span>Giải thích sau khi trả lời</span><textarea value={selected.explanation ?? ""} onChange={event => updateQuestion({ ...selected, explanation: event.target.value })} placeholder="Vì sao đây là đáp án đúng?"/></label></section>
      <aside className="question-settings"><header>Cài đặt câu hỏi</header><SelectField label="Loại câu hỏi" value={selected.type} onChange={value => changeType(value as TriviaQuestionType)}>{Object.entries(questionTypeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</SelectField><SelectField label="Thời gian" value={selected.timeLimitSeconds} onChange={value => updateQuestion({ ...selected, timeLimitSeconds: Number(value) })}>{triviaTimerPresets.map(value => <option value={value} key={value}>{value} giây</option>)}</SelectField><SelectField label="Chế độ điểm" value={selected.scoringMode} onChange={value => updateQuestion({ ...selected, scoringMode: value as TriviaQuestion["scoringMode"] })}><option value="STANDARD">Chuẩn · tối đa 1000</option><option value="ACCURACY_ONLY">Chỉ độ chính xác · 1000</option><option value="DOUBLE_POINTS">Nhân đôi · tối đa 2000</option><option value="NO_POINTS">Không tính điểm</option></SelectField><SelectField label="Độ khó" value={selected.difficulty} onChange={value => updateQuestion({ ...selected, difficulty: value as TriviaQuestion["difficulty"] })}><option value="EASY">Dễ</option><option value="MEDIUM">Trung bình</option><option value="HARD">Khó</option></SelectField><label className="builder-field"><span>Danh mục</span><input value={selected.category ?? ""} onChange={event => updateQuestion({ ...selected, category: event.target.value })}/></label><label className="setting-toggle"><input type="checkbox" checked={selected.config.allowAnswerChanges ?? false} onChange={event => updateQuestion({ ...selected, config: { ...selected.config, allowAnswerChanges: event.target.checked } })}/><span/><div>Cho phép đổi đáp án<small>Mặc định tắt để khóa ngay khi gửi</small></div></label><hr/><header>Cài đặt bộ quiz</header><SelectField label="Hiển thị" value={quiz.visibility} onChange={value => setQuiz({ ...quiz, visibility: value as TriviaQuiz["visibility"] })}><option value="PRIVATE">Riêng tư</option><option value="UNLISTED">Không công khai</option><option value="PUBLIC">Công khai</option></SelectField><label className="setting-toggle"><input type="checkbox" checked={quiz.settings.shuffleQuestions} onChange={event => setQuiz({ ...quiz, settings: { ...quiz.settings, shuffleQuestions: event.target.checked } })}/><span/><div>Trộn câu hỏi</div></label><label className="setting-toggle"><input type="checkbox" checked={quiz.settings.shuffleAnswers} onChange={event => setQuiz({ ...quiz, settings: { ...quiz.settings, shuffleAnswers: event.target.checked } })}/><span/><div>Trộn đáp án</div></label><label className="setting-toggle"><input type="checkbox" checked={quiz.settings.autoAdvance} onChange={event => setQuiz({ ...quiz, settings: { ...quiz.settings, autoAdvance: event.target.checked } })}/><span/><div>Tự động chuyển câu</div></label></aside>
    </div>{showAi && <AiGenerator onClose={() => setShowAi(false)} onGenerated={questions => { setQuiz(current => ({ ...current, questions })); setSelectedId(questions[0]?.id ?? ""); setNotice("Đã tạo bản nháp AI — hãy kiểm tra từng câu trước khi lưu."); }}/>}</main>;
}
