"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { PrivateRoomState, PublicRoomState } from "../lib/realtime";
import type { TriviaAnswerPayload } from "../lib/trivia";
import { calculatePotentialScore, getTriviaScoreRange } from "../lib/trivia-score";
import { emitWithAck } from "../lib/socket";
import { GameStatusBanner, Scoreboard } from "./game-ui";

function usePotentialScore(room: PublicRoomState, lockedScore?: number) {
  const trivia = room.trivia; const question = trivia?.question; const [snapshot, setSnapshot] = useState({ score: lockedScore ?? 0, remainingMs: 0, ratio: 0 }); const offsetRef = useRef(0);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (!trivia) return; offsetRef.current = trivia.serverNow - Date.now(); let frame = 0; const render = () => { const now = Date.now() + offsetRef.current; const startedAt = trivia.questionStartedAt ?? now; const endsAt = trivia.questionEndsAt ?? now; const duration = Math.max(1, endsAt - startedAt); const remainingMs = trivia.phase === "paused" ? (trivia.pausedRemainingMs ?? 0) : Math.max(0, endsAt - now); const ratio = Math.max(0, Math.min(1, remainingMs / duration)); const range = getTriviaScoreRange(question?.scoringMode); const score = lockedScore ?? (question?.scoringMode === "ACCURACY_ONLY" ? 1000 : calculatePotentialScore({ startedAt, endsAt, currentTime: now, ...range })); setSnapshot({ score, remainingMs, ratio: lockedScore !== undefined ? Math.max(0, Math.min(1, lockedScore / Math.max(1, range.maxScore))) : ratio }); if (remainingMs > 0 && lockedScore === undefined && trivia.phase === "answering") frame = requestAnimationFrame(render); }; render(); return () => cancelAnimationFrame(frame); }, [trivia?.serverNow, trivia?.questionStartedAt, trivia?.questionEndsAt, trivia?.phase, trivia?.pausedRemainingMs, question?.scoringMode, lockedScore]);
  return snapshot;
}

function PotentialScore({ room, lockedScore }: { room: PublicRoomState; lockedScore?: number }) {
  const { score, remainingMs, ratio } = usePotentialScore(room, lockedScore); const state = score > 700 ? "healthy" : score > 400 ? "warning" : "urgent";
  return <section className={`potential-score ${state} ${lockedScore !== undefined ? "locked" : ""}`}><div><span>{lockedScore !== undefined ? "Điểm đã khóa" : "Điểm có thể nhận"}</span><strong>{score.toLocaleString("vi-VN")}</strong><em>điểm</em></div><div className="potential-track"><i style={{ transform: `scaleX(${ratio})` }}/></div><small>{lockedScore !== undefined ? "✓ Đáp án đã được máy chủ ghi nhận" : `${(remainingMs / 1000).toFixed(1)} giây`}</small></section>;
}

function ChoiceAnswers({ room, selected, onSelect, disabled }: { room: PublicRoomState; selected: string[]; onSelect: (ids: string[]) => void; disabled: boolean }) {
  const question = room.trivia!.question!; const multiple = question.type === "MULTIPLE_CHOICE";
  return <div className={`trivia-choice-grid ${question.type === "TRUE_FALSE" ? "true-false" : ""}`}>{question.options.map((option, index) => { const active = selected.includes(option.id); return <button disabled={disabled} className={`trivia-choice choice-${index % 6} ${active ? "selected" : ""}`} key={option.id} onClick={() => onSelect(multiple ? (active ? selected.filter(id => id !== option.id) : [...selected, option.id]) : [option.id])}>{option.imageUrl && <img src={option.imageUrl} alt=""/>}<span>{option.emoji ?? ["◆", "●", "▲", "■"][index % 4]}</span><strong>{option.text}</strong><i>{active ? "✓" : String.fromCharCode(65 + index)}</i></button>; })}</div>;
}

function PlayerAnswerControl({ room, onSubmit, disabled }: { room: PublicRoomState; onSubmit: (answer: TriviaAnswerPayload) => void; disabled: boolean }) {
  const question = room.trivia!.question!; const [selected, setSelected] = useState<string[]>([]); const [text, setText] = useState(""); const [number, setNumber] = useState(""); const [scale, setScale] = useState(question.config.scaleMinimum ?? 1); const [order, setOrder] = useState(question.options.map(option => option.id)); const [matches, setMatches] = useState<Record<string,string>>({});
  if (["SINGLE_CHOICE", "TRUE_FALSE", "IMAGE_CHOICE", "POLL"].includes(question.type)) return <ChoiceAnswers room={room} selected={selected} onSelect={ids => { setSelected(ids); if (!disabled && ids.length) onSubmit({ optionIds: ids }); }} disabled={disabled}/>;
  if (question.type === "MULTIPLE_CHOICE") return <div><ChoiceAnswers room={room} selected={selected} onSelect={setSelected} disabled={disabled}/><button className="button trivia-submit" disabled={disabled || !selected.length} onClick={() => onSubmit({ optionIds: selected })}>✓ Chốt {selected.length} đáp án</button></div>;
  if (question.type === "TEXT_INPUT") return <form className="trivia-text-answer" onSubmit={event => { event.preventDefault(); onSubmit({ text }); }}><input value={text} onChange={event => setText(event.target.value)} placeholder="Nhập câu trả lời…" autoComplete="off"/><button className="button" disabled={disabled || !text.trim()}>Chốt đáp án →</button></form>;
  if (question.type === "NUMBER_INPUT") return <form className="trivia-text-answer number" onSubmit={event => { event.preventDefault(); onSubmit({ number: Number(number) }); }}><input type="number" value={number} onChange={event => setNumber(event.target.value)} placeholder="168"/><button className="button" disabled={disabled || number === ""}>Chốt đáp án →</button></form>;
  if (question.type === "SCALE") return <div className="trivia-scale"><strong>{scale}</strong><input type="range" min={question.config.scaleMinimum ?? 1} max={question.config.scaleMaximum ?? 10} step={question.config.scaleStep ?? 1} value={scale} onChange={event => setScale(Number(event.target.value))}/><div><span>{question.config.scaleMinimumLabel}</span><span>{question.config.scaleMaximumLabel}</span></div><button className="button" disabled={disabled} onClick={() => onSubmit({ scale })}>Chốt lựa chọn</button></div>;
  if (question.type === "ORDER") return <div className="trivia-order"><p>Chạm mũi tên để sắp xếp đúng thứ tự</p>{order.map((id, index) => { const option = question.options.find(item => item.id === id); return <div key={id}><b>{index + 1}</b><span>{option?.text}</span><button disabled={index === 0} onClick={() => { const next = [...order]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; setOrder(next); }}>↑</button><button disabled={index === order.length - 1} onClick={() => { const next = [...order]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; setOrder(next); }}>↓</button></div>; })}<button className="button" disabled={disabled} onClick={() => onSubmit({ order })}>✓ Chốt thứ tự</button></div>;
  if (question.type === "MATCHING") return <div className="trivia-matching"><p>Ghép từng mục với đáp án phù hợp</p>{question.options.map(option => <div key={option.id}><strong>{option.text}</strong><input placeholder="Nhập cặp tương ứng" value={matches[option.id] ?? ""} onChange={event => setMatches(current => ({ ...current, [option.id]: event.target.value }))}/></div>)}<button className="button" disabled={disabled || Object.keys(matches).length !== question.options.length} onClick={() => onSubmit({ matches })}>✓ Chốt các cặp</button></div>;
  return null;
}

function RevealPanel({ room, privateState }: { room: PublicRoomState; privateState: PrivateRoomState | null }) {
  const trivia = room.trivia!; const question = trivia.question!; const result = privateState?.triviaSubmission; const reveal = trivia.reveal; const total = Object.values(reveal?.distribution ?? {}).reduce((sum, value) => sum + value, 0);
  return <div className="trivia-reveal"><GameStatusBanner icon="✦" tone="success">Câu trả lời đúng là…</GameStatusBanner><h1>{question.prompt}</h1>{question.options.length > 0 && <div className="reveal-options">{question.options.map(option => { const count = Object.entries(reveal?.distribution ?? {}).filter(([key]) => key.split("|").includes(option.id)).reduce((sum, [, value]) => sum + value, 0); const correct = reveal?.correctOptionIds?.includes(option.id); return <div className={correct ? "correct" : ""} key={option.id}><span>{correct ? "✓" : ""}</span><strong>{option.text}</strong><div><i style={{ width: `${total ? count / total * 100 : 0}%` }}/></div><b>{total ? Math.round(count / total * 100) : 0}%</b></div>; })}</div>}<div className={`personal-result ${result?.correct ? "correct" : result?.correct === false ? "wrong" : "poll"}`}><span>{result?.correct ? "✓" : result?.correct === false ? "✕" : "●"}</span><div><small>Kết quả của bạn</small><strong>{result?.correct ? "Chính xác!" : result?.correct === false ? "Chưa đúng" : "Đã ghi nhận"}</strong><p>{result?.responseTimeMs ? `${(result.responseTimeMs / 1000).toFixed(2)} giây` : "Không có câu trả lời"}</p></div><b>+{result?.awardedScore ?? 0}</b></div>{reveal?.explanation && <aside className="answer-explanation"><span>💡</span><div><strong>Giải thích</strong><p>{reveal.explanation}</p></div></aside>}</div>;
}

function Leaderboard({ room }: { room: PublicRoomState }) {
  const trivia = room.trivia!; const ranked = [...room.players].sort((a, b) => b.score - a.score);
  return <div className="trivia-leaderboard"><span className="winner-crown">🏆</span><p className="table-kicker">Bảng xếp hạng</p><h1>Ai đang dẫn đầu?</h1><div>{ranked.map((player, index) => { const previous = trivia.previousRanks[player.id] ?? index + 1; const movement = previous - (index + 1); return <article key={player.id} className={index === 0 ? "leader" : ""}><b>{index + 1}</b><span>{player.name.slice(0, 2).toUpperCase()}</span><div><strong>{player.name}</strong>{(trivia.streaks[player.id] ?? 0) >= 2 && <small>🔥 {trivia.streaks[player.id]} câu đúng liên tiếp</small>}</div><em>{movement > 0 ? `▲ +${movement}` : movement < 0 ? `▼ ${movement}` : "—"}</em><strong>{player.score.toLocaleString("vi-VN")}</strong></article>; })}</div></div>;
}

function TriviaFinal({ room, privateState, isHost, onRestart }: { room: PublicRoomState; privateState: PrivateRoomState | null; isHost: boolean; onRestart: () => void }) {
  const [reviewOpen, setReviewOpen] = useState(false); const review = privateState?.triviaReview ?? []; const correct = review.filter(item => item.correct).length; const fastest = review.length ? Math.min(...review.filter(item => item.responseTimeMs > 0).map(item => item.responseTimeMs)) : 0;
  return <div className="trivia-final"><Scoreboard players={room.players} winnerLabel="Nhà vô địch Trivia"/><div className="trivia-final-stats"><div><strong>{correct} / {review.length}</strong><span>Câu đúng</span></div><div><strong>{review.length ? Math.round(correct / review.length * 100) : 0}%</strong><span>Độ chính xác</span></div><div><strong>{fastest ? `${(fastest / 1000).toFixed(2)}s` : "—"}</strong><span>Nhanh nhất</span></div></div><div className="final-actions">{isHost && <button className="button" onClick={onRestart}>↻ Chơi lại</button>}<Link className="button secondary" href="/trivia">Đổi bộ câu hỏi</Link><Link className="button secondary" href="/">Về sảnh</Link><button className="button secondary" onClick={() => setReviewOpen(value => !value)}>Xem chi tiết</button></div>{reviewOpen && <div className="trivia-review">{review.map((item, index) => <article key={item.questionId}><header><span>Câu {index + 1}</span><b className={item.correct ? "correct" : "wrong"}>{item.correct ? "✓" : "✕"} +{item.points}</b></header><h3>{item.prompt}</h3><p>Bạn chọn: <strong>{item.playerAnswer}</strong></p><p>Đáp án: <strong>{item.correctAnswer}</strong></p><small>{(item.responseTimeMs / 1000).toFixed(2)} giây</small></article>)}</div>}</div>;
}

export function TriviaGamePanel({ room, privateState, isHost, onError }: { room: PublicRoomState; privateState: PrivateRoomState | null; isHost: boolean; onError: (message: string) => void }) {
  const trivia = room.trivia; if (!trivia) return null; const submission = privateState?.triviaSubmission; const locked = submission && submission.questionId === trivia.question?.id ? submission.potentialScore : undefined;
  async function send(event: "trivia:reveal" | "trivia:next" | "trivia:skip" | "trivia:pause" | "trivia:restart") { const result = await emitWithAck(event, {}); if (!result.ok) onError(result.error); }
  async function submit(answer: TriviaAnswerPayload) { const result = await emitWithAck<{ potentialScore: number; submittedAt: number }>("trivia:submit-answer", { answer }); if (!result.ok) onError(result.error); }
  if (trivia.phase === "intro") return <div className="trivia-intro"><span>Câu {trivia.questionIndex + 1} / {trivia.questionCount}</span><i>{trivia.question?.category ? "🌍" : "🧠"}</i><small>{trivia.question?.category ?? "TRIVIA"}</small><h1>Sẵn sàng chưa?</h1></div>;
  if (trivia.phase === "leaderboard") return <div><Leaderboard room={room}/>{isHost && <button className="button trivia-next" onClick={() => send("trivia:next")}>Câu tiếp theo →</button>}</div>;
  if (trivia.phase === "finished") return <TriviaFinal room={room} privateState={privateState} isHost={isHost} onRestart={() => void send("trivia:restart")}/>;
  if (trivia.phase === "reveal") return <div><RevealPanel room={room} privateState={privateState}/>{isHost && <button className="button trivia-next" onClick={() => send("trivia:next")}>Xem bảng xếp hạng →</button>}</div>;
  const answered = locked !== undefined; const question = trivia.question;
  return <div className={`trivia-active ${trivia.phase === "paused" ? "paused" : ""}`}><header><span>Câu {trivia.questionIndex + 1} / {trivia.questionCount}</span><b>{question?.category ?? "TRIVIA"}</b><em>{room.answeredPlayerIds.length} / {room.players.length} đã trả lời</em></header><PotentialScore room={room} lockedScore={locked}/><section className="trivia-question"><h1>{question?.prompt}</h1>{question?.description && <p>{question.description}</p>}{question?.media?.url && <img src={question.media.url} alt={question.media.alt ?? "Minh họa câu hỏi"}/>}</section>{trivia.phase === "paused" ? <div className="trivia-paused"><span>Ⅱ</span><strong>Đã tạm dừng</strong><small>Điểm và thời gian đang được giữ nguyên.</small></div> : answered ? <div className="answer-locked"><span>✓</span><strong>Đã chốt đáp án</strong><p>Đáp án của bạn đang được giữ bí mật.</p></div> : <PlayerAnswerControl room={room} onSubmit={submit} disabled={answered}/>} {isHost && <div className="trivia-host-controls"><button onClick={() => send("trivia:pause")}>{trivia.phase === "paused" ? "▶ Tiếp tục" : "Ⅱ Tạm dừng"}</button><button onClick={() => send("trivia:skip")}>Bỏ qua</button><button onClick={() => send("trivia:reveal")}>Công bố đáp án</button></div>}</div>;
}
