import type { TriviaQuestion, TriviaQuiz } from "./trivia";
import { defaultTriviaSettings } from "./trivia";

const now = "2026-07-22T00:00:00.000Z";

const optionQuestion = (
  id: string,
  prompt: string,
  answers: Array<[string, boolean]>,
  extras: Partial<TriviaQuestion> = {},
): TriviaQuestion => ({
  id,
  type: "SINGLE_CHOICE",
  prompt,
  options: answers.map(([text, correct], index) => ({
    id: `${id}-${index + 1}`,
    text,
    correct,
  })),
  config: { shuffleAnswers: true, allowAnswerChanges: false },
  timeLimitSeconds: 20,
  scoringMode: "STANDARD",
  difficulty: "MEDIUM",
  tags: [],
  ...extras,
});

export const starterTriviaQuizzes: TriviaQuiz[] = [
  {
    id: "kien-thuc-tong-hop",
    title: "Kiến thức tổng hợp",
    description: "Từ địa lý đến khoa học — một vòng đấu nhanh dành cho mọi hội bạn.",
    coverEmoji: "🧠",
    category: "Kiến thức",
    language: "vi",
    visibility: "PUBLIC",
    creator: "Luki Minigame",
    plays: 1284,
    createdAt: now,
    updatedAt: now,
    settings: { ...defaultTriviaSettings },
    questions: [
      optionQuestion(
        "general-1",
        "Thủ đô của Nhật Bản là gì?",
        [["Tokyo", true], ["Osaka", false], ["Kyoto", false], ["Nagoya", false]],
        { category: "Địa lý", difficulty: "EASY", explanation: "Tokyo là thủ đô và đô thị đông dân nhất Nhật Bản." },
      ),
      optionQuestion(
        "general-2",
        "Quốc gia nào có diện tích lớn nhất thế giới?",
        [["Canada", false], ["Nga", true], ["Mỹ", false], ["Trung Quốc", false]],
        { category: "Địa lý", explanation: "Nga có diện tích khoảng 17,1 triệu km²." },
      ),
      {
        id: "general-3",
        type: "MULTIPLE_CHOICE",
        prompt: "Những hành tinh nào sau đây là hành tinh khí khổng lồ?",
        description: "Chọn tất cả đáp án đúng.",
        options: [
          { id: "general-3-jupiter", text: "Sao Mộc", correct: true },
          { id: "general-3-saturn", text: "Sao Thổ", correct: true },
          { id: "general-3-earth", text: "Trái Đất", correct: false },
          { id: "general-3-mars", text: "Sao Hỏa", correct: false },
        ],
        config: { shuffleAnswers: true, allowAnswerChanges: false },
        timeLimitSeconds: 30,
        scoringMode: "STANDARD",
        difficulty: "MEDIUM",
        category: "Khoa học",
        tags: ["vũ trụ"],
        explanation: "Sao Mộc và Sao Thổ chủ yếu được cấu tạo từ hydro và heli.",
      },
      {
        id: "general-4",
        type: "TRUE_FALSE",
        prompt: "Ánh sáng truyền nhanh hơn âm thanh.",
        options: [
          { id: "general-4-true", text: "Đúng", emoji: "✓", correct: true },
          { id: "general-4-false", text: "Sai", emoji: "✕", correct: false },
        ],
        config: { allowAnswerChanges: false },
        timeLimitSeconds: 10,
        scoringMode: "STANDARD",
        difficulty: "EASY",
        category: "Khoa học",
        tags: [],
      },
      {
        id: "general-5",
        type: "NUMBER_INPUT",
        prompt: "Một tuần có bao nhiêu giờ?",
        options: [],
        config: { numberMode: "EXACT", numberAnswer: 168, tolerance: 0, allowAnswerChanges: false },
        timeLimitSeconds: 20,
        scoringMode: "DOUBLE_POINTS",
        difficulty: "EASY",
        category: "Tính nhanh",
        tags: [],
        explanation: "7 ngày × 24 giờ = 168 giờ.",
      },
      {
        id: "general-6",
        type: "ORDER",
        prompt: "Sắp xếp các hành tinh từ gần Mặt Trời nhất.",
        options: [
          { id: "general-6-earth", text: "Trái Đất", order: 2 },
          { id: "general-6-mercury", text: "Sao Thủy", order: 0 },
          { id: "general-6-venus", text: "Sao Kim", order: 1 },
          { id: "general-6-mars", text: "Sao Hỏa", order: 3 },
        ],
        config: {
          correctOrder: ["general-6-mercury", "general-6-venus", "general-6-earth", "general-6-mars"],
          allowAnswerChanges: false,
        },
        timeLimitSeconds: 45,
        scoringMode: "STANDARD",
        difficulty: "MEDIUM",
        category: "Vũ trụ",
        tags: [],
      },
    ],
  },
  {
    id: "viet-nam-trong-toi",
    title: "Việt Nam trong tôi",
    description: "Ẩm thực, địa danh và văn hóa Việt Nam qua những câu hỏi vui.",
    coverEmoji: "🇻🇳",
    category: "Việt Nam",
    language: "vi",
    visibility: "PUBLIC",
    creator: "Cộng đồng Luki",
    plays: 932,
    createdAt: now,
    updatedAt: now,
    settings: { ...defaultTriviaSettings, leaderboardFrequency: "EVERY_3" },
    questions: [
      optionQuestion("vn-1", "Vịnh Hạ Long thuộc tỉnh nào?", [["Quảng Ninh", true], ["Hải Phòng", false], ["Thanh Hóa", false], ["Đà Nẵng", false]], { category: "Địa lý", difficulty: "EASY" }),
      {
        id: "vn-2",
        type: "TEXT_INPUT",
        prompt: "Điền tên thành phố được mệnh danh là “thành phố ngàn hoa”.",
        options: [],
        config: {
          acceptedAnswers: ["Đà Lạt", "Da Lat", "Dalat"],
          caseInsensitive: true,
          accentInsensitive: true,
          trimWhitespace: true,
          allowAnswerChanges: false,
        },
        timeLimitSeconds: 30,
        scoringMode: "STANDARD",
        difficulty: "EASY",
        category: "Du lịch",
        tags: [],
      },
      optionQuestion("vn-3", "Món ăn nào thường được cuốn bằng bánh tráng?", [["Gỏi cuốn", true], ["Bún bò", false], ["Cơm tấm", false], ["Bánh canh", false]], { category: "Ẩm thực", difficulty: "EASY" }),
    ],
  },
  {
    id: "hoi-ban-than",
    title: "Hội bạn hiểu nhau tới đâu?",
    description: "Bình chọn, dự đoán và tranh luận — không cần kiến thức sách vở.",
    coverEmoji: "🎉",
    category: "Party",
    language: "vi",
    visibility: "PUBLIC",
    creator: "Luki Minigame",
    plays: 2140,
    createdAt: now,
    updatedAt: now,
    settings: { ...defaultTriviaSettings, shuffleAnswers: false },
    questions: [
      {
        id: "party-1",
        type: "POLL",
        prompt: "Nếu được du lịch ngay bây giờ, bạn sẽ chọn đâu?",
        options: [
          { id: "party-1-japan", text: "Nhật Bản", emoji: "🇯🇵" },
          { id: "party-1-korea", text: "Hàn Quốc", emoji: "🇰🇷" },
          { id: "party-1-thailand", text: "Thái Lan", emoji: "🇹🇭" },
          { id: "party-1-france", text: "Pháp", emoji: "🇫🇷" },
        ],
        config: { allowAnswerChanges: false },
        timeLimitSeconds: 20,
        scoringMode: "NO_POINTS",
        difficulty: "EASY",
        category: "Bình chọn",
        tags: [],
      },
      {
        id: "party-2",
        type: "SCALE",
        prompt: "Bạn thích đồ cay đến mức nào?",
        options: [],
        config: {
          scaleMinimum: 1,
          scaleMaximum: 10,
          scaleStep: 1,
          scaleMinimumLabel: "Không thích",
          scaleMaximumLabel: "Rất thích",
          allowAnswerChanges: false,
        },
        timeLimitSeconds: 20,
        scoringMode: "NO_POINTS",
        difficulty: "EASY",
        category: "Ý kiến",
        tags: [],
      },
    ],
  },
];
